[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux"]

[font]
size = 12.0

[font.normal]
family = "Noto Sans Mono"
style = "Regular"

[window]
dynamic_title = true
title = "Alacritty"
